import { useCallback, useEffect, useState } from "react";
import { RefreshCw, Settings2 } from "lucide-react";
import PricingSection from "../../components/settings/PricingSection";
import PreferenceSection from "../../components/settings/PreferenceSection";
import ProcessETASection from "../../components/settings/ProcessETASection";
import SecuritySection from "../../components/settings/SecuritySection";
import { getSettings, saveSettings } from "../API/settingsAPI";

const defaults = { dark_mode: false, notifications_enabled: true, bundle_size: 9, bundle_price: 200, excess_price: 30, addon_price: 9, washing_minutes: 30, drying_minutes: 45, folding_minutes: 15, require_strong_password: true, session_timeout_minutes: 30 };
export default function Settings() {
  const [settings, setSettings] = useState(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { setLoading(true); setError(""); const data = await getSettings(); setSettings({ ...defaults, ...data }); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { document.documentElement.classList.toggle("app-dark", settings.dark_mode); localStorage.setItem("ic-dark-mode", String(settings.dark_mode)); return () => document.documentElement.classList.remove("app-dark"); }, [settings.dark_mode]);
  const change = (name, value) => setSettings((current) => ({ ...current, [name]: value }));
  const save = async (fields, success) => { const payload = Object.fromEntries(fields.map((field) => [field, settings[field]])); try { setSaving(true); setError(""); const saved = await saveSettings(payload); setSettings((current) => ({ ...current, ...saved })); setMessage(success); } catch (requestError) { setError(requestError.message); throw requestError; } finally { setSaving(false); } };
  const savePreference = async (name, value) => { const previous = settings[name]; change(name, value); try { setSaving(true); const saved = await saveSettings({ [name]: value }); setSettings((current) => ({ ...current, ...saved })); setMessage(`${name === "dark_mode" ? "Appearance" : "Notification"} setting saved.`); } catch (requestError) { change(name, previous); setError(requestError.message); } finally { setSaving(false); } };
  return <main className="settings-page"><div className="settings-shell"><header className="settings-header"><div><span className="settings-eyebrow"><Settings2 size={15} /> System configuration</span><h1>Settings</h1><p>Manage preferences, operational timing, pricing, and security.</p></div><button type="button" className="btn btn-secondary" onClick={load} disabled={loading}><RefreshCw size={17} /> Refresh</button></header>{message && <div role="status" className="settings-message">{message}<button aria-label="Close success message" onClick={() => setMessage("")}>×</button></div>}{error && <div role="alert" className="settings-error">{error}<button onClick={load}>Try again</button></div>}{loading ? <div className="settings-loading">Loading settings...</div> : <div className="settings-layout"><PreferenceSection darkMode={settings.dark_mode} notifications={settings.notifications_enabled} onDarkModeChange={(value) => savePreference("dark_mode", value)} onNotificationsChange={(value) => savePreference("notifications_enabled", value)} /><ProcessETASection values={settings} onChange={change} saving={saving} onSave={() => save(["washing_minutes", "drying_minutes", "folding_minutes"], "ETA settings saved successfully.")} /><PricingSection values={settings} saving={saving} onSave={(values) => { setSettings((current) => ({ ...current, ...values })); return saveSettings(values).then((saved) => { setSettings((current) => ({ ...current, ...saved })); setMessage("Pricing saved successfully."); }).catch((requestError) => setError(requestError.message)); }} /><SecuritySection values={settings} onChange={change} saving={saving} onSave={() => save(["require_strong_password", "session_timeout_minutes"], "Security settings saved successfully.")} /></div>}</div></main>;
}
